### PR TITLE
fix some troubleshooting questions ...

### PR DESCRIPTION
**Pull request by Giiome**
see http://docs.rubygems.org/read/chapter/19

### CODE REVIEW

**Comment by mebens** [comment]
I'm not quite sure how that relates to what was added; perhaps I missed something. I do know that Jekyll already requires RubyGems, and I have no idea why you would need to require the require_relative function.

**Comment by Giiome** [comment]
well perhaps i miss something too, but I had some errors with this require_relative which had been resolved by this patch.

**Comment by mebens** [comment]
Can you tell what those errors were?

**Comment by Giiome** [comment]
ia had this kind of error: 
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- RedCloth (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
    from -e:1

but that was not with RedCloth

**Comment by mebens** [comment]
Are you using Ruby 1.8 or something? If so, it's probably a compatibility issue of sort, since I'm using 1.9.

**Comment by Giiome** [comment]
my ruby version is up to date at this moment : 
    ruby -v
    ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-darwin11.3.0]

**Comment by mebens** [comment]
That's strange. I thought it was Ruby 1.8 because of that file path you quoted (`... Ruby/Site/1.8/rubygems ...`). Anyway, I think I'll add these in, just without the `require 'rubygems'` bit.

**Comment by Giiome** [comment]
Well i hope that will  help.
my quote was from this site http://docs.rubygems.org/read/chapter/19 not from my log.

**Comment by mebens** [comment]
Thanks for contributing! :)

**Pull request merged**
